"""initial schema

Revision ID: 0001_initial_schema
Revises: 
Create Date: 2026-09-08 15:59:14.390327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.

revision: str = '0001_initial_schema'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(sa.text('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"'))
    op.execute(sa.text('CREATE EXTENSION IF NOT EXISTS "pg_trgm"'))
    op.execute(sa.text('CREATE SEQUENCE IF NOT EXISTS global_work_item_serial_seq START WITH 1 INCREMENT BY 1'))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('iso2', sa.CHAR(length=2), nullable=False),
    sa.Column('iso3', sa.CHAR(length=3), nullable=False),
    sa.Column('phone_code', sa.String(length=10), nullable=True),
    sa.Column('timezone', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('flag_emoji', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('countries_pkey')),
    sa.UniqueConstraint('iso2', name='countries_iso2_key'),
    sa.UniqueConstraint('iso3', name='countries_iso3_key')
    )
    op.create_table('organizations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('domain', sa.String(length=150), nullable=False),
    sa.Column('industry', sa.String(length=150), nullable=False),
    sa.Column('team_size', sa.Text(), nullable=False),
    sa.Column('country', sa.Text(), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('organizations_pkey')),
    sa.UniqueConstraint('name', name='uni_organizations_name'),
    sa.UniqueConstraint('slug', name='uni_organizations_slug')
    )
    op.create_index('idx_organization_deleted_at', 'organizations', ['deleted_at'], unique=False)
    op.create_index('idx_organization_name', 'organizations', ['name'], unique=False)
    op.create_index('idx_organization_slug', 'organizations', ['slug'], unique=True)
    op.create_table('orphaned_files',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('orphaned_files_pkey'))
    )
    op.create_index('idx_orphaned_files_available', 'orphaned_files', ['available_at', 'created_at'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('resource', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('permissions_pkey'))
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('refresh_tokens_pkey')),
    sa.UniqueConstraint('token_hash', name='uni_refresh_tokens_token_hash'),
    sa.UniqueConstraint('user_id', name='uni_refresh_tokens_user_id')
    )
    op.create_index('idx_refresh_tokens_deleted_at', 'refresh_tokens', ['deleted_at'], unique=False)
    op.create_index('idx_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('roles_pkey'))
    )
    op.create_index('idx_roles_deleted_at', 'roles', ['deleted_at'], unique=False)
    op.create_index('idx_roles_organization_id', 'roles', ['organization_id'], unique=False)
    op.create_table('organization_invitations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('role_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_organization_invitations_organization'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='fk_organization_invitations_role'),
    sa.PrimaryKeyConstraint('id', name=op.f('organization_invitations_pkey')),
    sa.UniqueConstraint('token', name='uni_organization_invitations_token')
    )
    op.create_index('idx_org_invites_deleted_at', 'organization_invitations', ['deleted_at'], unique=False)
    op.create_index('idx_org_invites_email', 'organization_invitations', ['email'], unique=False)
    op.create_index('idx_org_invites_org_id', 'organization_invitations', ['organization_id'], unique=False)
    op.create_index('idx_org_invites_token', 'organization_invitations', ['token'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('permission_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name='fk_role_permissions_permission'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='fk_role_permissions_role'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('role_permissions_pkey'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('role_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('color', sa.String(length=7), server_default='#3498DB', nullable=False),
    sa.Column('timezone', sa.String(length=50), server_default='UTC', nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('require_password_change', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_users_organization'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='fk_users_role'),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name='uni_users_email'),
    sa.UniqueConstraint('username', name='uni_users_username')
    )
    op.create_index('idx_users_deleted_at', 'users', ['deleted_at'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_organization_id', 'users', ['organization_id'], unique=False)
    op.create_index('idx_users_role_id', 'users', ['role_id'], unique=False)
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_projects_creator'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_projects_organization'),
    sa.PrimaryKeyConstraint('id', name=op.f('projects_pkey'))
    )
    op.create_index('idx_projects_created_by', 'projects', ['created_by'], unique=False)
    op.create_index('idx_projects_deleted_at', 'projects', ['deleted_at'], unique=False)
    op.create_index('idx_projects_slug', 'projects', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('comments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('task_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('user_story_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_comment_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.id'], name='fk_comments_parent_comment'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_comments_project'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_comments_user'),
    sa.PrimaryKeyConstraint('id', name=op.f('comments_pkey'))
    )
    op.create_index('idx_comments_deleted_at', 'comments', ['deleted_at'], unique=False)
    op.create_index('idx_comments_organization_id', 'comments', ['organization_id'], unique=False)
    op.create_index('idx_comments_parent_comment_id', 'comments', ['parent_comment_id'], unique=False)
    op.create_index('idx_comments_project_id', 'comments', ['project_id'], unique=False)
    op.create_index('idx_comments_task_id', 'comments', ['task_id'], unique=False)
    op.create_index('idx_comments_user_id', 'comments', ['user_id'], unique=False)
    op.create_index('idx_comments_user_story_id', 'comments', ['user_story_id'], unique=False)
    op.create_table('custom_statuses',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_final', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_custom_statuses_project'),
    sa.PrimaryKeyConstraint('id', name=op.f('custom_statuses_pkey'))
    )
    op.create_index('idx_custom_statuses_deleted_at', 'custom_statuses', ['deleted_at'], unique=False)
    op.create_index('idx_custom_statuses_project_id', 'custom_statuses', ['project_id'], unique=False)
    op.create_table('labels',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_labels_project'),
    sa.PrimaryKeyConstraint('id', name=op.f('labels_pkey'))
    )
    op.create_index('idx_labels_deleted_at', 'labels', ['deleted_at'], unique=False)
    op.create_index('idx_labels_project_id', 'labels', ['project_id'], unique=False)
    op.create_index('idx_project_label_name', 'labels', ['project_id', 'name'], unique=True)
    op.create_table('project_members',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_role', sa.String(length=50), nullable=True),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('added_by_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role_id', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], name='fk_project_members_added_by'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_project_members_project'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='fk_project_members_role'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_project_members_user'),
    sa.PrimaryKeyConstraint('id', name=op.f('project_members_pkey'))
    )
    op.create_index('idx_project_members_deleted_at', 'project_members', ['deleted_at'], unique=False)
    op.create_index('idx_project_members_role_id', 'project_members', ['role_id'], unique=False)
    op.create_table('sprints',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('goal', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='planned', nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.DateTime(), nullable=True),
    sa.Column('velocity', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='fk_sprints_created_by'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_sprints_project'),
    sa.PrimaryKeyConstraint('id', name=op.f('sprints_pkey'))
    )
    op.create_index('idx_sprints_deleted_at', 'sprints', ['deleted_at'], unique=False)
    op.create_index('idx_sprints_project_id', 'sprints', ['project_id'], unique=False)
    op.create_table('task_attachments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('task_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), server_default="'::text", nullable=False),
    sa.Column('uploaded_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='task_attachments_project_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('task_attachments_pkey'))
    )
    op.create_index('idx_task_attachments_project_id', 'task_attachments', ['project_id'], unique=False)
    op.create_index('idx_task_attachments_task_id', 'task_attachments', ['task_id'], unique=False)
    op.create_index('idx_task_attachments_uploaded_by', 'task_attachments', ['uploaded_by'], unique=False)
    op.create_table('user_story_attachments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('user_story_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), server_default="'::text", nullable=False),
    sa.Column('uploaded_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='user_story_attachments_project_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_story_attachments_pkey'))
    )
    op.create_index('idx_user_story_attachments_project_id', 'user_story_attachments', ['project_id'], unique=False)
    op.create_index('idx_user_story_attachments_uploaded_by', 'user_story_attachments', ['uploaded_by'], unique=False)
    op.create_index('idx_user_story_attachments_user_story_id', 'user_story_attachments', ['user_story_id'], unique=False)
    op.create_table('user_story_statuses',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_closed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_final', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_user_story_statuses_project'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_story_statuses_pkey'))
    )
    op.create_index('idx_user_story_statuses_deleted_at', 'user_story_statuses', ['deleted_at'], unique=False)
    op.create_index('idx_user_story_statuses_project_id', 'user_story_statuses', ['project_id'], unique=False)
    op.create_table('comment_attachments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('comment_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('task_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('user_story_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), server_default="'::text", nullable=False),
    sa.Column('uploaded_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name='fk_comments_attachments'),
    sa.PrimaryKeyConstraint('id', name=op.f('comment_attachments_pkey'))
    )
    op.create_index('idx_comment_attachments_comment_id', 'comment_attachments', ['comment_id'], unique=False)
    op.create_index('idx_comment_attachments_task_id', 'comment_attachments', ['task_id'], unique=False)
    op.create_index('idx_comment_attachments_uploaded_by', 'comment_attachments', ['uploaded_by'], unique=False)
    op.create_index('idx_comment_attachments_user_story_id', 'comment_attachments', ['user_story_id'], unique=False)
    op.create_table('sprint_snapshots',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sprint_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_story_points', sa.Integer(), nullable=False),
    sa.Column('remaining_story_points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], name='fk_sprint_snapshots_sprint'),
    sa.PrimaryKeyConstraint('id', name=op.f('sprint_snapshots_pkey'))
    )
    op.create_index('idx_sprint_snapshot_sprint_date', 'sprint_snapshots', ['date'], unique=True)
    op.create_index('idx_sprint_snapshots_sprint_id', 'sprint_snapshots', ['sprint_id'], unique=False)
    op.create_table('user_stories',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sprint_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('serial_number', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=50), server_default='medium', nullable=False),
    sa.Column('status_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('story_points', sa.Integer(), server_default='0', nullable=False),
    sa.Column('backlog_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('assignee_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('reporter_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_closed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('key', sa.String(length=50), server_default="'::character varying", nullable=True),
    sa.Column('sequence_number', sa.Integer(), server_default='0', nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name='fk_user_stories_assignee'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_user_stories_project'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name='fk_user_stories_reporter'),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], name='fk_user_stories_sprint'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_stories_pkey'))
    )
    op.create_index('idx_project_user_story_key', 'user_stories', ['project_id', 'key'], unique=True)
    op.create_index('idx_user_stories_assignee_id', 'user_stories', ['assignee_id'], unique=False)
    op.create_index('idx_user_stories_deleted_at', 'user_stories', ['deleted_at'], unique=False)
    op.create_index('idx_user_stories_project_id', 'user_stories', ['project_id'], unique=False)
    op.create_index('idx_user_stories_reporter_id', 'user_stories', ['reporter_id'], unique=False)
    op.create_index('idx_user_stories_sequence_number', 'user_stories', ['sequence_number'], unique=False)
    op.create_index('idx_user_stories_serial_number', 'user_stories', ['serial_number'], unique=True)
    op.create_index('idx_user_stories_sprint_id', 'user_stories', ['sprint_id'], unique=False)
    op.create_index('idx_user_stories_status_id', 'user_stories', ['status_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sprint_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('user_story_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), server_default='task', nullable=False),
    sa.Column('priority', sa.String(length=50), server_default='medium', nullable=False),
    sa.Column('status_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='todo', nullable=False),
    sa.Column('assignee_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('reporter_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('story_points', sa.Integer(), server_default='0', nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_hours', sa.Numeric(), nullable=True),
    sa.Column('actual_hours', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name='fk_tasks_assignee'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_tasks_project'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name='fk_tasks_reporter'),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], name='fk_tasks_sprint'),
    sa.ForeignKeyConstraint(['user_story_id'], ['user_stories.id'], name='fk_tasks_user_story'),
    sa.PrimaryKeyConstraint('id', name=op.f('tasks_pkey'))
    )
    op.create_index('idx_project_task_key', 'tasks', ['project_id', 'key'], unique=True)
    op.create_index('idx_tasks_assignee_id', 'tasks', ['assignee_id'], unique=False)
    op.create_index('idx_tasks_deleted_at', 'tasks', ['deleted_at'], unique=False)
    op.create_index('idx_tasks_project_id', 'tasks', ['project_id'], unique=False)
    op.create_index('idx_tasks_reporter_id', 'tasks', ['reporter_id'], unique=False)
    op.create_index('idx_tasks_sequence_number', 'tasks', ['sequence_number'], unique=False)
    op.create_index('idx_tasks_serial_number', 'tasks', ['serial_number'], unique=True)
    op.create_index('idx_tasks_sprint_id', 'tasks', ['sprint_id'], unique=False)
    op.create_index('idx_tasks_status_id', 'tasks', ['status_id'], unique=False)
    op.create_index('idx_tasks_user_story_id', 'tasks', ['user_story_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('task_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('sprint_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('user_story_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_audit_logs_project'),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], name='fk_audit_logs_sprint'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='fk_audit_logs_task'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_audit_logs_user'),
    sa.ForeignKeyConstraint(['user_story_id'], ['user_stories.id'], name='fk_audit_logs_user_story'),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    op.create_index('idx_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_logs_org_id', 'audit_logs', ['organization_id'], unique=False)
    op.create_index('idx_audit_logs_project_id', 'audit_logs', ['project_id'], unique=False)
    op.create_index('idx_audit_logs_resource_type', 'audit_logs', ['resource_type'], unique=False)
    op.create_index('idx_audit_logs_sprint_id', 'audit_logs', ['sprint_id'], unique=False)
    op.create_index('idx_audit_logs_task_id', 'audit_logs', ['task_id'], unique=False)
    op.create_index('idx_audit_logs_type', 'audit_logs', ['type'], unique=False)
    op.create_index('idx_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index('idx_audit_logs_user_story_id', 'audit_logs', ['user_story_id'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('user_story_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('task_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='fk_favorites_task'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_favorites_user'),
    sa.ForeignKeyConstraint(['user_story_id'], ['user_stories.id'], name='fk_favorites_user_story'),
    sa.PrimaryKeyConstraint('id', name=op.f('favorites_pkey'))
    )
    op.create_index('idx_favorites_deleted_at', 'favorites', ['deleted_at'], unique=False)
    op.create_index('idx_favorites_task_id', 'favorites', ['task_id'], unique=False)
    op.create_index('idx_favorites_user_id', 'favorites', ['user_id'], unique=False)
    op.create_index('idx_favorites_user_story_id', 'favorites', ['user_story_id'], unique=False)
    op.create_table('task_labels',
    sa.Column('task_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('label_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], name='fk_task_labels_label'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='fk_task_labels_task'),
    sa.PrimaryKeyConstraint('task_id', 'label_id', name=op.f('task_labels_pkey'))
    )
    op.execute(sa.text("CREATE INDEX IF NOT EXISTS idx_users_fts ON users USING gin(to_tsvector('english', coalesce(full_name, '') || ' ' || coalesce(email, '') || ' ' || coalesce(username, '')))"))
    op.execute(sa.text("CREATE INDEX IF NOT EXISTS idx_projects_fts ON projects USING gin(to_tsvector('english', coalesce(name, '') || ' ' || coalesce(description, '') || ' ' || coalesce(slug, '')))"))
    op.execute(sa.text("CREATE INDEX IF NOT EXISTS idx_sprints_fts ON sprints USING gin(to_tsvector('english', coalesce(name, '') || ' ' || coalesce(goal, '')))"))
    op.execute(sa.text("CREATE INDEX IF NOT EXISTS idx_tasks_fts ON tasks USING gin(to_tsvector('english', coalesce(title, '') || ' ' || coalesce(description, '') || ' ' || coalesce(key, '')))"))
    op.execute(sa.text("CREATE INDEX IF NOT EXISTS idx_user_stories_fts ON user_stories USING gin(to_tsvector('english', coalesce(title, '') || ' ' || coalesce(description, '') || ' ' || coalesce(key, '')))"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(sa.text("DROP INDEX IF EXISTS idx_user_stories_fts"))
    op.execute(sa.text("DROP INDEX IF EXISTS idx_tasks_fts"))
    op.execute(sa.text("DROP INDEX IF EXISTS idx_sprints_fts"))
    op.execute(sa.text("DROP INDEX IF EXISTS idx_projects_fts"))
    op.execute(sa.text("DROP INDEX IF EXISTS idx_users_fts"))
    op.execute(sa.text("DROP SEQUENCE IF EXISTS global_work_item_serial_seq"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_labels')
    op.drop_index('idx_favorites_user_story_id', table_name='favorites')
    op.drop_index('idx_favorites_user_id', table_name='favorites')
    op.drop_index('idx_favorites_task_id', table_name='favorites')
    op.drop_index('idx_favorites_deleted_at', table_name='favorites')
    op.drop_table('favorites')
    op.drop_index('idx_audit_logs_user_story_id', table_name='audit_logs')
    op.drop_index('idx_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('idx_audit_logs_type', table_name='audit_logs')
    op.drop_index('idx_audit_logs_task_id', table_name='audit_logs')
    op.drop_index('idx_audit_logs_sprint_id', table_name='audit_logs')
    op.drop_index('idx_audit_logs_resource_type', table_name='audit_logs')
    op.drop_index('idx_audit_logs_project_id', table_name='audit_logs')
    op.drop_index('idx_audit_logs_org_id', table_name='audit_logs')
    op.drop_index('idx_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('idx_tasks_user_story_id', table_name='tasks')
    op.drop_index('idx_tasks_status_id', table_name='tasks')
    op.drop_index('idx_tasks_sprint_id', table_name='tasks')
    op.drop_index('idx_tasks_serial_number', table_name='tasks')
    op.drop_index('idx_tasks_sequence_number', table_name='tasks')
    op.drop_index('idx_tasks_reporter_id', table_name='tasks')
    op.drop_index('idx_tasks_project_id', table_name='tasks')
    op.drop_index('idx_tasks_deleted_at', table_name='tasks')
    op.drop_index('idx_tasks_assignee_id', table_name='tasks')
    op.drop_index('idx_project_task_key', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('idx_user_stories_status_id', table_name='user_stories')
    op.drop_index('idx_user_stories_sprint_id', table_name='user_stories')
    op.drop_index('idx_user_stories_serial_number', table_name='user_stories')
    op.drop_index('idx_user_stories_sequence_number', table_name='user_stories')
    op.drop_index('idx_user_stories_reporter_id', table_name='user_stories')
    op.drop_index('idx_user_stories_project_id', table_name='user_stories')
    op.drop_index('idx_user_stories_deleted_at', table_name='user_stories')
    op.drop_index('idx_user_stories_assignee_id', table_name='user_stories')
    op.drop_index('idx_project_user_story_key', table_name='user_stories')
    op.drop_table('user_stories')
    op.drop_index('idx_sprint_snapshots_sprint_id', table_name='sprint_snapshots')
    op.drop_index('idx_sprint_snapshot_sprint_date', table_name='sprint_snapshots')
    op.drop_table('sprint_snapshots')
    op.drop_index('idx_comment_attachments_user_story_id', table_name='comment_attachments')
    op.drop_index('idx_comment_attachments_uploaded_by', table_name='comment_attachments')
    op.drop_index('idx_comment_attachments_task_id', table_name='comment_attachments')
    op.drop_index('idx_comment_attachments_comment_id', table_name='comment_attachments')
    op.drop_table('comment_attachments')
    op.drop_index('idx_user_story_statuses_project_id', table_name='user_story_statuses')
    op.drop_index('idx_user_story_statuses_deleted_at', table_name='user_story_statuses')
    op.drop_table('user_story_statuses')
    op.drop_index('idx_user_story_attachments_user_story_id', table_name='user_story_attachments')
    op.drop_index('idx_user_story_attachments_uploaded_by', table_name='user_story_attachments')
    op.drop_index('idx_user_story_attachments_project_id', table_name='user_story_attachments')
    op.drop_table('user_story_attachments')
    op.drop_index('idx_task_attachments_uploaded_by', table_name='task_attachments')
    op.drop_index('idx_task_attachments_task_id', table_name='task_attachments')
    op.drop_index('idx_task_attachments_project_id', table_name='task_attachments')
    op.drop_table('task_attachments')
    op.drop_index('idx_sprints_project_id', table_name='sprints')
    op.drop_index('idx_sprints_deleted_at', table_name='sprints')
    op.drop_table('sprints')
    op.drop_index('idx_project_members_role_id', table_name='project_members')
    op.drop_index('idx_project_members_deleted_at', table_name='project_members')
    op.drop_table('project_members')
    op.drop_index('idx_project_label_name', table_name='labels')
    op.drop_index('idx_labels_project_id', table_name='labels')
    op.drop_index('idx_labels_deleted_at', table_name='labels')
    op.drop_table('labels')
    op.drop_index('idx_custom_statuses_project_id', table_name='custom_statuses')
    op.drop_index('idx_custom_statuses_deleted_at', table_name='custom_statuses')
    op.drop_table('custom_statuses')
    op.drop_index('idx_comments_user_story_id', table_name='comments')
    op.drop_index('idx_comments_user_id', table_name='comments')
    op.drop_index('idx_comments_task_id', table_name='comments')
    op.drop_index('idx_comments_project_id', table_name='comments')
    op.drop_index('idx_comments_parent_comment_id', table_name='comments')
    op.drop_index('idx_comments_organization_id', table_name='comments')
    op.drop_index('idx_comments_deleted_at', table_name='comments')
    op.drop_table('comments')
    op.drop_index('idx_projects_slug', table_name='projects', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_projects_deleted_at', table_name='projects')
    op.drop_index('idx_projects_created_by', table_name='projects')
    op.drop_table('projects')
    op.drop_index('idx_users_username', table_name='users')
    op.drop_index('idx_users_role_id', table_name='users')
    op.drop_index('idx_users_organization_id', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_deleted_at', table_name='users')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_index('idx_org_invites_token', table_name='organization_invitations')
    op.drop_index('idx_org_invites_org_id', table_name='organization_invitations')
    op.drop_index('idx_org_invites_email', table_name='organization_invitations')
    op.drop_index('idx_org_invites_deleted_at', table_name='organization_invitations')
    op.drop_table('organization_invitations')
    op.drop_index('idx_roles_organization_id', table_name='roles')
    op.drop_index('idx_roles_deleted_at', table_name='roles')
    op.drop_table('roles')
    op.drop_index('idx_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_deleted_at', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('permissions')
    op.drop_index('idx_orphaned_files_available', table_name='orphaned_files')
    op.drop_table('orphaned_files')
    op.drop_index('idx_organization_slug', table_name='organizations')
    op.drop_index('idx_organization_name', table_name='organizations')
    op.drop_index('idx_organization_deleted_at', table_name='organizations')
    op.drop_table('organizations')
    op.drop_table('countries')
    # ### end Alembic commands ###
